# Generated by Django 5.1 on 2024-08-25 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=200)),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.IntegerField(unique=True)),
                ('foto', models.ImageField(upload_to='fotos_candidatos/')),
                ('partido', models.CharField(max_length=50)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('fiscal', 'Fiscal')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos_validos', models.IntegerField()),
                ('votos_branco', models.IntegerField()),
                ('votos_nulos', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_apuracao/')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.candidato')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.cargo')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.secao')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('fiscal', 'Fiscal')], max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.secao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
