# Generated by Django 5.1 on 2024-08-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0002_remove_usuario_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Admin'), ('fiscal', 'Fiscal')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
